### ISSUE TITLE
Missing LICENSE file in the repo of ver 1.0.5

### ISSUE THREAD

**Issue by itsuki-murata** [jbgutierrez/path-parse#23]
Currently I'm using path-parse version 1.0.5, but can't find a LICENSE file in the repo of ver 1.0.5.
Could you add the LICENSE file in the repo of ver 1.0.5?
Or is it possible to use the LICENSE file of the latest version as the license for ver 1.0.5?
Thanks in advance.

**Comment by ljharb** [comment]
Seems simpler to just upgrade to v1.0.7?

**Comment by itsuki-murata** [comment]
Thank you for your reply.
I'll consider upgrading to v1.0.7.
Thank you.
