### ISSUE TITLE
Querystring as ext

### ISSUE THREAD

**Issue by RWOverdijk** [jbgutierrez/path-parse#7]
```js
pathParse('https://res.cloudinary.com/some/path.mp3?hello=world')

{ root: '',
  dir: 'https://res.cloudinary.com/some',
  base: 'path.mp3?hello=world',
  ext: '.mp3?hello=world',
  name: 'path' }
```

I know this isn't technically a "path" but I wouldn't expect the querystring to be a part of the ext.

**Comment by AndrusGerman** [comment]
pathParse is designed to detect paths (Directories), from windows and Unix.  If you want me to detect URL paths, you could add a request or contribution to the project.

**Comment by RWOverdijk** [comment]
Haha, I can't even remember why I needed this. I'm pretty sure I just ended up solving it some other way 😄
